server:
    port: 8083
spring:
    application:
        name: TaskApplication
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/task
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:123456}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        jwt:
            secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
            expiration-time: 3600000  # 1h in milliseconds

dubbo:
    application:
#        logger: slf4j
        name: ${spring.application.name}
        qos-enable: false
    registry:
        address: nacos://${NACOS_HOST:localhost}:${NACOS_PORT:8848}
    protocol:
        name: dubbo
        port: 20893
    consumer:
        filter: -authenticationPrepare

seata:
    enabled: true
    application-id: dubbo-samples-seata
    tx-service-group: default_tx_group
    service:
        vgroup-mapping:
            default_tx_group: default
    registry:
        type: nacos
        nacos:
            application: seata-server
            server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
            group: SEATA_GROUP
            namespace: ""
            username: ""
            password: ""
    config:
        type: nacos
        nacos:
            server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
            group: SEATA_GROUP
            namespace: ""
            username: ""
            password: ""
