version: "3"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - app_network
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./nacos/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
    networks:
      - app_network
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - app_network

  seata-server:
    image: seataio/seata-server:${SEATA_VERSION}
    hostname: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=${HOST_IP}
    volumes:
      # - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"        #设置系统时区
      # - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"  #设置时区
      - "./seata/application.yml:/seata-server/resources/application.yml"
    networks:
      - app_network
    depends_on:
      - nacos
      - postgres

  postgres:
    image: postgres:latest
    container_name: seata-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pm_assistant
    ports:
      - "5433:5432"
    volumes:
      - "D:/postgresql/data:/var/lib/postgresql/data"
      - "./script/db:/docker-entrypoint-initdb.d"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
