seata:
  # config:
  # support: nacos, consul, apollo, zk, etcd3
  # type: file
  # registry:
  # support: nacos, eureka, redis, zk, consul, etcd3, sofa
  # type: file
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP
      context-path:
      username:
      password:
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username:
      password: